"use strict";

try{
   let x = 10;
    // miFuncion();
}
catch(error){
    console.log("Error" + ": "+ error);
}
finally{
    console.log("Termina la revisi√≥n de errores.")
}

console.log("Continuamos...")